### ISSUE TITLE
Build system improvement to use pybind-setuptools instead

### ISSUE THREAD

**Issue by russkel** [russkel/python-moos#3]
https://pybind11.readthedocs.io/en/stable/compiling.html#building-with-setuptools

Should mirror the example project: https://github.com/pybind/python_example

**Comment by russkel** [comment]
WIP: https://github.com/russkel/python-moos/tree/ci-actions

**Comment by oviquezr** [comment]
Started playing with the Actions stack for the build – looks like the "composite" actions need explicit "run" statements, so the earlier attempt was failing when trying to use `actions/checkout@v2`
New file pip_v2.yml in branch oviquezr-patch-1 keeps all instructions in one place for each workflow, but seems to move forward to the build. Currently failing to locate MOOSMsg.h in the tree; should be fixable with a cmake flag

**Comment by russkel** [comment]
Groan, I found that out last night as well. Also feel free to commit directly to the ci-actions branch should you wish.

**Comment by russkel** [comment]
Pip install now finishes completely. Conda packages are being created fine. Wheels are being created for OSX fine.

Wheels still have an issue on Linux due to some linking issue which I don't fully understand yet. I need to increase verbosity and check it out.

Conda artifacts are also not being correctly uploaded to Actions workflow, might be an issue with my wildcard paths.

Once these are sorted we can automatically publish to PyPI!

**Comment by oviquezr** [comment]
I've been playing with this a little today. After a handful of failures, here's what I have:
- cibuildwheel runs on Docker, and pulls an array of images ([see here](https://github.com/joerick/cibuildwheel/blob/master/cibuildwheel/linux.py#L46))
- The linker relates to the assimilated MOOS build, but might be running a different architecture on the Docker image

So, here is my **question**: do we need to rebuild MOOS for each arch, inside the cibuildwheel docker ?

**Comment by russkel** [comment]
> So, here is my **question**: do we need to rebuild MOOS for each arch, inside the cibuildwheel docker ?

I got annoyed at the prospect of having two scripts to compile MOOS.. so I devised a better idea. I am going to move the compiling of MOOS to the MOOS repository and upload packages to a bintray repository. Then we simply add the bintray apt repos and install the desired package instead of trying to compile it for each architecture.

I will upload my work on this soon.

May as well do MOOS-IvP while we're at it.

**Comment by oviquezr** [comment]
Sounds good to me! I tried a few more tweaks to have it build MOOS in each container, but I'm guessing there's something about docker that's acting funny -- it seems it is building, but not installing correctly. The option of going with apt install per arch sounds waaaay better

**Comment by russkel** [comment]
> Sounds good to me! I tried a few more tweaks to have it build MOOS in each container, but I'm guessing there's something about docker that's acting funny -- it seems it is building, but not installing correctly. The option of going with apt install per arch sounds waaaay better

Yeah I don't know what's going on here - it doesn't look like it is linking correctly, hence not finding the symbols. Just had a thought - it's probably the GCC versions/ABI incompatibility.

**Comment by russkel** [comment]
https://github.com/russkel/moos_pkg/actions/runs/414502199

Tada!

**Comment by oviquezr** [comment]
Nice!!

Though, I haven't quite found quite how to access the deb package as an "artifact" on GitHub. It'll be nice to have that be part of the solution, I bet -- I expect it should make things a good deal faster, on the multilinux part of the wheels workflow...

Not sure why calling `cmake --install . --prefix <dest>` in the docker unit wasn't actually installing anything. Since the build succeeds, I went with the brute-force fix of pointing to the new build's lib and the original build's include... I got the current wheels setup (rebuilding for each flavor of linux) to move into the tests, but the docker unit didn't seem to find MOOSDB.

So, `cmake --install ` didnt work; I then tried using `make install` in the docker stack and it's moved further than before. We'll have to see how far it goes

**Comment by russkel** [comment]
I need to push these onto bintray. I kind of forgot about this. I will try and get it working.

**Comment by oviquezr** [comment]
For what it’s worth: the last build completed successfully! Tho I don’t
think it posted to PyPI since it wasn’t tagged as a release.

**Comment by russkel** [comment]
Awesome work. I will squash all these commits and merge them in. Thanks for working on that.

**Comment by oviquezr** [comment]
Looks like changing `cibuildwheels` versions pointed to a copy of `manylinux` that didn't have `cmake`, so the MOOS build itself was failing. Changing to `manylinux2014` seems to have solved that problem.

**Comment by russkel** [comment]
Good find. I have updated to latest version of cibuildwheel, added QEMU initialisation and building of aarch64 wheels.

**Comment by oviquezr** [comment]
@russkel Looks like this might be ready to squash/merge/release – what do you think?

**Comment by russkel** [comment]
I think you're right. I'll get on it.

**Comment by russkel** [comment]
Okay, done! Waiting for CI to finish and then I will set as release and see if it pushes up to pypi.

**Comment by russkel** [comment]
https://pypi.org/project/pymoos/2021.1/#files

Success!

**Comment by russkel** [comment]
Thanks for your help Oscar.

Now we can fully build/publish with ease.
